-- AddForeignKey
ALTER TABLE "Match" ADD CONSTRAINT "Match_teamA_fkey" FOREIGN KEY ("teamA") REFERENCES "Team"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Match" ADD CONSTRAINT "Match_teamB_fkey" FOREIGN KEY ("teamB") REFERENCES "Team"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
